const { DataTypes } = require("sequelize");
const sequelize = require("../config/database");

const Package = sequelize.define(
  "Package",
  {
    id: { type: DataTypes.BIGINT.UNSIGNED, autoIncrement: true, primaryKey: true },
    name: { type: DataTypes.STRING, allowNull: false },
    description: { type: DataTypes.TEXT },
    invoice_description: { type: DataTypes.TEXT },
    service_type: { type: DataTypes.INTEGER },
    policy_group: { type: DataTypes.STRING },
    allocation_group: { type: DataTypes.STRING },
    extra_fee_group: { type: DataTypes.STRING },
    status: { type: DataTypes.INTEGER },
    reseller_status: { type: DataTypes.INTEGER },
    expiration_status: { type: DataTypes.INTEGER },
    invoice_status: { type: DataTypes.INTEGER },
    auto_invoice_generate_status: { type: DataTypes.INTEGER },
    auto_invoice_date: { type: DataTypes.DATE },
    self_activation_status: { type: DataTypes.INTEGER },
    leftover_days_status: { type: DataTypes.INTEGER },
    billing_type: { type: DataTypes.INTEGER },
    duration: { type: DataTypes.INTEGER },
    duration_type: { type: DataTypes.INTEGER },
    isp_id: { type: DataTypes.INTEGER },
    branch_id: { type: DataTypes.INTEGER },
    pool_type: { type: DataTypes.INTEGER },
    pool: { type: DataTypes.STRING },
    expired_pool: { type: DataTypes.STRING },
    next_expired_action_type: { type: DataTypes.INTEGER },
    next_disable_action_type: { type: DataTypes.INTEGER },
    next_package: { type: DataTypes.INTEGER },
    next_expired_package: { type: DataTypes.INTEGER },
    next_disable_package: { type: DataTypes.INTEGER },
    next_expired_policy: { type: DataTypes.STRING },
    next_disable_policy: { type: DataTypes.STRING },
    bandwidth: { type: DataTypes.INTEGER },
    bandwidth_type: { type: DataTypes.INTEGER },
    data_qt_status: { type: DataTypes.INTEGER },
    data_qt_vol: { type: DataTypes.INTEGER },
    data_qt_over_status: { type: DataTypes.INTEGER },
    data_qt_over_type: { type: DataTypes.INTEGER },
    data_fup_status: { type: DataTypes.INTEGER },
    data_fup_vol: { type: DataTypes.INTEGER },
    data_fup_bw_limit: { type: DataTypes.STRING },
    session_qt_status: { type: DataTypes.INTEGER },
    session_qt_time: { type: DataTypes.INTEGER },
    session_qt_over_status: { type: DataTypes.INTEGER },
    session_qt_over_type: { type: DataTypes.INTEGER },
    session_fup_status: { type: DataTypes.INTEGER },
    session_fup_vol: { type: DataTypes.INTEGER },
    session_fup_bw_limit: { type: DataTypes.STRING },
    fixed_expiry_day: { type: DataTypes.INTEGER },
    fixed_expiry_day_status: { type: DataTypes.INTEGER },
    fixed_expiry_day_acct_status: { type: DataTypes.INTEGER },
    fixed_expiry_day_acct_type: { type: DataTypes.INTEGER },
    fixed_expiry_time: { type: DataTypes.STRING },
    fixed_expiry_time_status: { type: DataTypes.INTEGER },
    auto_renew_status: { type: DataTypes.INTEGER },
    auto_payment_status: { type: DataTypes.INTEGER },
    custom_expiry_status: { type: DataTypes.INTEGER },
    custom_expiry_type: { type: DataTypes.INTEGER },
    allow_captive_portal: { type: DataTypes.INTEGER },
    created_by: { type: DataTypes.INTEGER },
    updated_by: { type: DataTypes.INTEGER },
    created_at: { type: DataTypes.DATE },
    updated_at: { type: DataTypes.DATE },
  },
  {
    tableName: "packages",
    timestamps: false,
  }
);

module.exports = Package;
