const { DataTypes } = require("sequelize");
const sequelize = require("../config/database");

const Subscriber = sequelize.define(
  "Subscriber",
  {
    id: { type: DataTypes.BIGINT.UNSIGNED, autoIncrement: true, primaryKey: true },
    fullname: { type: DataTypes.STRING, allowNull: false },
    username: { type: DataTypes.STRING, allowNull: false, unique: true },
    password: { type: DataTypes.STRING, allowNull: false },
    connection_username: { type: DataTypes.STRING },
    connection_password: { type: DataTypes.STRING },
    identity: { type: DataTypes.STRING },
    phone: { type: DataTypes.STRING, allowNull: false },
    email: { type: DataTypes.STRING(100), allowNull: false, unique: true },
    email_verified_at: { type: DataTypes.DATE },
    address: { type: DataTypes.STRING },
    photo: { type: DataTypes.STRING },
    salesperson_id: { type: DataTypes.INTEGER, allowNull: false },
    package_id: { type: DataTypes.INTEGER, allowNull: false },
    secondary_package_id: { type: DataTypes.INTEGER },
    country: { type: DataTypes.INTEGER },
    province: { type: DataTypes.INTEGER },
    city: { type: DataTypes.INTEGER },
    area: { type: DataTypes.INTEGER },
    subarea: { type: DataTypes.INTEGER },
    latitude: { type: DataTypes.STRING },
    longitude: { type: DataTypes.STRING },
    department: { type: DataTypes.INTEGER },
    area_group: { type: DataTypes.STRING },
    isp_id: { type: DataTypes.INTEGER },
    branch_id: { type: DataTypes.INTEGER },
    otp_status: { type: DataTypes.INTEGER },
    invoice_status: { type: DataTypes.INTEGER },
    self_registration_status: { type: DataTypes.INTEGER },
    self_activation_status: { type: DataTypes.INTEGER },
    credentials_reset_status: { type: DataTypes.INTEGER },
    allow_volume_status: { type: DataTypes.INTEGER },
    login_log_status: { type: DataTypes.INTEGER },
    usage_log_status: { type: DataTypes.INTEGER },
    profile_map_status: { type: DataTypes.INTEGER },
    profile_documents_status: { type: DataTypes.INTEGER },
    activation_packages_status: { type: DataTypes.INTEGER },
    profile_status: { type: DataTypes.INTEGER },
    sms_status: { type: DataTypes.INTEGER },
    email_status: { type: DataTypes.INTEGER },
    auto_payment_status: { type: DataTypes.INTEGER },
    auto_renew_status: { type: DataTypes.INTEGER },
    mac_lock_status: { type: DataTypes.INTEGER },
    mac_address: { type: DataTypes.STRING },
    static_ip_status: { type: DataTypes.INTEGER },
    ip_pool_id: { type: DataTypes.INTEGER },
    ip_address_id: { type: DataTypes.INTEGER },
    static_ip: { type: DataTypes.STRING },
    nas_id: { type: DataTypes.INTEGER },
    nas_group: { type: DataTypes.STRING },
    connection_type: { type: DataTypes.INTEGER },
    connection_status: { type: DataTypes.INTEGER, defaultValue: 1 },
    service_type: { type: DataTypes.INTEGER },
    box_number: { type: DataTypes.STRING },
    box_address: { type: DataTypes.STRING },
    uplink_port: { type: DataTypes.STRING },
    fiber_code: { type: DataTypes.STRING },
    fiber_color: { type: DataTypes.STRING },
    switch_board: { type: DataTypes.STRING },
    switch_port: { type: DataTypes.STRING },
    backup_connection: { type: DataTypes.STRING },
    electric_socket: { type: DataTypes.STRING },
    cable_type: { type: DataTypes.STRING },
    created_by_id: { type: DataTypes.INTEGER },
    created_datetime: { type: DataTypes.DATE },
    last_login_time: { type: DataTypes.DATE },
    last_activation_time: { type: DataTypes.DATE },
    auto_renew_last_activation_date: { type: DataTypes.DATE },
    last_activated_by_id: { type: DataTypes.INTEGER },
    lock_volume_status: { type: DataTypes.INTEGER },
    total_data_quota: { type: DataTypes.INTEGER },
    used_data_quota: { type: DataTypes.INTEGER },
    used_data_collect_time: { type: DataTypes.DATE },
    lock_session_status: { type: DataTypes.INTEGER },
    total_session_quota: { type: DataTypes.INTEGER },
    used_session_quota: { type: DataTypes.INTEGER },
    used_session_collect_time: { type: DataTypes.DATE },
    last_interim_update: { type: DataTypes.DATE },
    expiration_date: { type: DataTypes.DATE },
    last_expiration_date: { type: DataTypes.DATE },
    discount_type: { type: DataTypes.INTEGER },
    discount: { type: DataTypes.DOUBLE(8, 2) },
    addition: { type: DataTypes.DOUBLE(8, 2) },
    subtraction: { type: DataTypes.DOUBLE(8, 2) },
    remember_token: { type: DataTypes.STRING(100) },
    signup_source: { type: DataTypes.INTEGER },
    expired_sms_status: { type: DataTypes.INTEGER },
    expired_email_status: { type: DataTypes.INTEGER },
    expiring_1day_sms_status: { type: DataTypes.INTEGER },
    expiring_3days_sms_status: { type: DataTypes.INTEGER },
    expiring_7days_sms_status: { type: DataTypes.INTEGER },
    expiring_1day_email_status: { type: DataTypes.INTEGER },
    expiring_3days_email_status: { type: DataTypes.INTEGER },
    expiring_7days_email_status: { type: DataTypes.INTEGER },
    grace_period_status: { type: DataTypes.INTEGER },
    grace_period_start_date: { type: DataTypes.DATE },
    grace_period_end_date: { type: DataTypes.DATE },
    join_date: { type: DataTypes.DATE },
    onu_note: { type: DataTypes.STRING },
    created_at: { type: DataTypes.DATE },
    updated_at: { type: DataTypes.DATE },
  },
  {
    tableName: "subscribers",
    timestamps: false,
  }
);

module.exports = Subscriber;
